name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dataworks:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/dataworks:latest ${{ secrets.DOCKER_USERNAME }}/dataworks:${{ github.sha }}
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dataworks:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dataworks:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dataworks:latest
            docker stop dataworks-container || true
            docker rm dataworks-container || true
            docker run -d --name dataworks-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/dataworks:latest
