name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dataworks:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/dataworks:latest ${{ secrets.DOCKER_USERNAME }}/dataworks:${{ github.sha }}
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dataworks:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dataworks:${{ github.sha }}